const { Addresses } = require("../src/schemas/addresses.js");
const { Restaurants } = require("../src/schemas/restaurants.js");
const { SeatingPlans } = require("../src/schemas/seatingPlans.js");
const { Bookings } = require("../src/schemas/bookings.js");
const { Promotions } = require("../src/schemas/promotions.js");
const { Reviews } = require("../src/schemas/reviews.js");
const { Menus } = require("../src/schemas/menus.js");

module.exports.LoadData = async () => {
  try {
    await Addresses.bulkCreate([
      {
        addressLine1: "123 Orchard Road",
        country: "Singapore",
        city: "Orchard",
        state: "Singapore",
        postalCode: "238801",
      },
      {
        addressLine1: "456 Marina Bay Street",
        country: "Singapore",
        city: "Marina Bay",
        state: "Singapore",
        postalCode: "018972",
      },
      {
        addressLine1: "789 Clementi Avenue 2",
        country: "Singapore",
        city: "Clementi",
        state: "Singapore",
        postalCode: "129603",
      },
      {
        addressLine1: "321 Bukit Merah View",
        country: "Singapore",
        city: "Bukit Merah",
        state: "Singapore",
        postalCode: "150321",
      },
      {
        addressLine1: "654 Bedok Reservoir Road",
        country: "Singapore",
        city: "Bedok",
        state: "Singapore",
        postalCode: "479261",
      },
      {
        addressLine1: "100 Raffles Avenue",
        country: "Singapore",
        city: "Raffles Place",
        state: "Singapore",
        postalCode: "039802",
      },
      {
        addressLine1: "200 River Valley Road",
        country: "Singapore",
        city: "River Valley",
        state: "Singapore",
        postalCode: "238379",
      },
      {
        addressLine1: "300 Tiong Bahru Road",
        country: "Singapore",
        city: "Tiong Bahru",
        state: "Singapore",
        postalCode: "168733",
      },
      {
        addressLine1: "400 Ang Mo Kio Avenue 1",
        country: "Singapore",
        city: "Ang Mo Kio",
        state: "Singapore",
        postalCode: "569494",
      },
    ]);

    await Restaurants.bulkCreate([
      {
        restaurantName: "Pasta Delights",
        description: "A place for all to enjoy homemade pasta",
        cuisine: "Italian",
        fkAddressId: 1,
        phone: "62345678",
        email: "contact@pasta.com",
        imageUrl:
          "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=1200&h=800&fit=crop",
        openingTime: "11:00:00",
        closingTime: "22:00:00",
      },
      {
        restaurantName: "The Garden Bistro",
        description: "An elegant French bistro offering classic dishes with a modern twist.",
        cuisine: "French",
        fkAddressId: 2,
        phone: "68123456",
        email: "reservations@gardenbistro.com",
        imageUrl:
          "https://images.unsplash.com/photo-1744313983217-e24a659bf7c1?w=1200&h=800&fit=crop",
        openingTime: "11:00:00",
        closingTime: "22:00:00",
      },
      {
        restaurantName: "Sakura Sushi & Grill",
        cuisine: "Japanese",
        description: "Fresh sushi and authentic Japanese cuisine in a contemporary setting.",
        fkAddressId: 3,
        phone: "64567890",
        email: "info@sakurasushi.com",
        imageUrl:
          "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=1200&h=800&fit=crop",
        openingTime: "12:00:00",
        closingTime: "23:00:00",
      },
      {
        restaurantName: "Mama Rosa's Trattoria",
        cuisine: "Italian",
        description: "Traditional Italian family recipes passed down through generations.",
        fkAddressId: 4,
        phone: "69876543",
        email: "ciao@mamarosas.com",
        imageUrl:
          "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1200&h=800&fit=crop",
        openingTime: "17:00:00",
        closingTime: "23:00:00",
      },
      {
        restaurantName: "Spice Route",
        cuisine: "Indian",
        description:
          "Authentic Indian cuisine with aromatic spices and traditional cooking methods.",
        fkAddressId: 5,
        phone: "63214567",
        email: "hello@spiceroute.com",
        imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&h=800&fit=crop",
        openingTime: "11:30:00",
        closingTime: "23:00:00",
      },
      {
        restaurantName: "La Bella Notte",
        description: "Modern Italian restaurant with handmade pasta and wood-fired pizzas.",
        cuisine: "Italian",
        fkAddressId: 6,
        phone: "64321098",
        email: "info@bellanotte.com",
        imageUrl:
          "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop",
        openingTime: "10:00:00",
        closingTime: "23:30:00",
      },
      {
        restaurantName: "Escargot & Cie",
        description:
          "Authentic Parisian French restaurant with classic cuisine and wine selection.",
        cuisine: "French",
        fkAddressId: 7,
        phone: "69876321",
        email: "reservations@escargotcie.com",
        imageUrl:
          "https://images.unsplash.com/photo-1602833334025-5019f046b8f7?w=1200&h=800&fit=crop",
        openingTime: "12:00:00",
        closingTime: "22:00:00",
      },
      {
        restaurantName: "Arigato Ramen House",
        description: "Cozy ramen bar serving authentic Japanese noodles and tonkotsu broths.",
        cuisine: "Japanese",
        fkAddressId: 8,
        phone: "61357924",
        email: "hello@arigatramen.com",
        imageUrl:
          "https://images.unsplash.com/photo-1538128844159-f08f41bfb169?w=1200&h=800&fit=crop",
        openingTime: "11:00:00",
        closingTime: "21:30:00",
      },
      {
        restaurantName: "Tandoori Dreams",
        description: "North Indian restaurant specializing in tandoor-cooked dishes and curries.",
        cuisine: "Indian",
        fkAddressId: 9,
        phone: "68246802",
        email: "dining@tandoridreams.com",
        imageUrl:
          "https://images.unsplash.com/photo-1697155836250-e3ba3a24fbd5?w=1200&h=800&fit=crop",
        openingTime: "12:00:00",
        closingTime: "23:00:00",
      },
    ]);

    await SeatingPlans.bulkCreate([
      {
        pax: 2,
        tableType: "indoor",
        tableNumber: "T1",
        fkRestaurantId: 1,
        x: 120,
        y: 80,
      },
      {
        pax: 4,
        tableType: "indoor",
        tableNumber: "T2",
        fkRestaurantId: 1,
        x: 220,
        y: 80,
      },
      {
        pax: 6,
        tableType: "vip",
        tableNumber: "VIP-1",
        fkRestaurantId: 1,
        x: 420,
        y: 200,
      },
      {
        pax: 2,
        tableType: "outdoor",
        tableNumber: "PATIO-1",
        fkRestaurantId: 1,
        x: 80,
        y: 260,
      },
      {
        pax: 4,
        tableType: "indoor",
        tableNumber: "T1",
        fkRestaurantId: 2,
        x: 140,
        y: 100,
      },
    ]);

    await Bookings.bulkCreate([
      {
        confirmationCode: "BK6F8K9J2L",
        customerName: "John Smith",
        customerEmail: "john.smith@email.com",
        customerPhone: "+1-555-1234",
        partySize: 2,
        specialRequests: "Window table preferred",
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "confirmed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK4N5M3P9X",
        customerName: "Sarah Johnson",
        customerEmail: "sarah.j@email.com",
        customerPhone: "+1-555-5678",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "pending",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7R2W5T8Q",
        customerName: "Michael Chen",
        customerEmail: "michael.chen@email.com",
        customerPhone: "+1-555-9012",
        partySize: 3,
        specialRequests: "Vegetarian options required",
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "confirmed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      // Ginna's Demo: 36 Bookings - The Garden Bistro - December 2024
      {
        confirmationCode: "BK8A1B2C3D",
        customerName: "Emily Davis",
        customerEmail: "emily.davis@email.com",
        customerPhone: "+1-555-2468",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-18",
        bookingTime: "19:30",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK9E4F5G6H",
        customerName: "Robert Wilson",
        customerEmail: "robert.w@email.com",
        customerPhone: "+1-555-1357",
        partySize: 4,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK1I7J8K9L",
        customerName: "Jessica Martinez",
        customerEmail: "jessica.m@email.com",
        customerPhone: "+1-555-9753",
        partySize: 3,
        specialRequests: "Allergic to shellfish",
        bookingDate: "2024-12-12",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2M0N1O2P",
        customerName: "David Brown",
        customerEmail: "david.brown@email.com",
        customerPhone: "+1-555-3579",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-10",
        bookingTime: "19:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK3Q4R5S6T",
        customerName: "Lisa Anderson",
        customerEmail: "lisa.a@email.com",
        customerPhone: "+1-555-7531",
        partySize: 5,
        specialRequests: "High chair needed",
        bookingDate: "2024-12-20",
        bookingTime: "17:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4U5V6W7P",
        customerName: "James Taylor",
        customerEmail: "james.t@email.com",
        customerPhone: "+1-555-8642",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-21",
        bookingTime: "18:45",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5Y6Z7A8B",
        customerName: "Patricia Lee",
        customerEmail: "patricia.lee@email.com",
        customerPhone: "+1-555-2468",
        partySize: 3,
        specialRequests: "Window seat preferred",
        bookingDate: "2024-12-22",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6C7D8E9F",
        customerName: "Thomas Garcia",
        customerEmail: "thomas.g@email.com",
        customerPhone: "+1-555-4820",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-09",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK7G8H9I0J",
        customerName: "Amanda White",
        customerEmail: "amanda.white@email.com",
        customerPhone: "+1-555-1928",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-08",
        bookingTime: "18:15",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8K9L0M1N",
        customerName: "Christopher Moore",
        customerEmail: "chris.moore@email.com",
        customerPhone: "+1-555-3746",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-23",
        bookingTime: "19:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK9O1P2Q3R",
        customerName: "Michelle Rodriguez",
        customerEmail: "michelle.r@email.com",
        customerPhone: "+1-555-5564",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-07",
        bookingTime: "20:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0S3T4U5V",
        customerName: "Kevin Jackson",
        customerEmail: "kevin.j@email.com",
        customerPhone: "+1-555-7382",
        partySize: 5,
        specialRequests: "Celebration dinner",
        bookingDate: "2024-12-24",
        bookingTime: "17:45",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK1A2B3C4D",
        customerName: "Olivia Green",
        customerEmail: "olivia.green@email.com",
        customerPhone: "+1-555-1235",
        partySize: 4,
        specialRequests: "Vegetarian meal",
        bookingDate: "2024-12-01",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2E3F4G5H",
        customerName: "Ethan Brown",
        customerEmail: "ethan.brown@email.com",
        customerPhone: "+1-555-6789",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-02",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3I4J5K6L",
        customerName: "Sophia White",
        customerEmail: "sophia.white@email.com",
        customerPhone: "+1-555-2468",
        partySize: 3,
        specialRequests: "Window seat",
        bookingDate: "2024-12-03",
        bookingTime: "20:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4M5N6O7P",
        customerName: "Liam Johnson",
        customerEmail: "liam.johnson@email.com",
        customerPhone: "+1-555-1357",
        partySize: 5,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-04",
        bookingTime: "17:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5Q6R7S8T",
        customerName: "Emma Davis",
        customerEmail: "emma.davis@email.com",
        customerPhone: "+1-555-9753",
        partySize: 6,
        specialRequests: null,
        bookingDate: "2024-12-05",
        bookingTime: "21:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6U7V8W9X",
        customerName: "Noah Wilson",
        customerEmail: "noah.wilson@email.com",
        customerPhone: "+1-555-3579",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-06",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7Y8Z9A1B",
        customerName: "Ava Martinez",
        customerEmail: "ava.martinez@email.com",
        customerPhone: "+1-555-7531",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-07",
        bookingTime: "15:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8C9D1E2F",
        customerName: "James Garcia",
        customerEmail: "james.garcia@email.com",
        customerPhone: "+1-555-8642",
        partySize: 3,
        specialRequests: "Allergic to peanuts",
        bookingDate: "2024-12-08",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK9G1H2I3J",
        customerName: "Isabella Rodriguez",
        customerEmail: "isabella.rodriguez@email.com",
        customerPhone: "+1-555-4820",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0K1L2M3N",
        customerName: "Benjamin Moore",
        customerEmail: "benjamin.moore@email.com",
        customerPhone: "+1-555-1928",
        partySize: 5,
        specialRequests: "High chair needed",
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK1O2P3Q4R",
        customerName: "Mia Taylor",
        customerEmail: "mia.taylor@email.com",
        customerPhone: "+1-555-5564",
        partySize: 4,
        specialRequests: "Vegan options",
        bookingDate: "2024-12-18",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2S3T4U5V",
        customerName: "Lucas Anderson",
        customerEmail: "lucas.anderson@email.com",
        customerPhone: "+1-555-7382",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3W4X5Y6Z",
        customerName: "Charlotte Lee",
        customerEmail: "charlotte.lee@email.com",
        customerPhone: "+1-555-2468",
        partySize: 2,
        specialRequests: "Window seat",
        bookingDate: "2024-12-19",
        bookingTime: "14:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4A5B6C7D",
        customerName: "Henry White",
        customerEmail: "henry.white@email.com",
        customerPhone: "+1-555-1235",
        partySize: 6,
        specialRequests: "Celebration dinner",
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5E6F7G8H",
        customerName: "Amelia Green",
        customerEmail: "amelia.green@email.com",
        customerPhone: "+1-555-6789",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6I7J8K9L",
        customerName: "Jack Brown",
        customerEmail: "jack.brown@email.com",
        customerPhone: "+1-555-1357",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7M8N9O1P",
        customerName: "Harper Johnson",
        customerEmail: "harper.johnson@email.com",
        customerPhone: "+1-555-9753",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "15:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8Q9R1S2T",
        customerName: "Ella Wilson",
        customerEmail: "ella.wilson@email.com",
        customerPhone: "+1-555-3579",
        partySize: 5,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK9U1V2W3X",
        customerName: "Alexander Martinez",
        customerEmail: "alex.martinez@email.com",
        customerPhone: "+1-555-7531",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-19",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0Z1Y2X3W",
        customerName: "Grace Lim",
        customerEmail: "grace.lim@email.com",
        customerPhone: "+1-555-2389",
        partySize: 2,
        specialRequests: "Anniversary celebration",
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK1T2U3V4W",
        customerName: "Daniel Ng",
        customerEmail: "daniel.ng@email.com",
        customerPhone: "+1-555-8492",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK2S3R4Q5P",
        customerName: "Fiona Tan",
        customerEmail: "fiona.tan@email.com",
        customerPhone: "+1-555-6734",
        partySize: 4,
        specialRequests: "Window seat preferred",
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3N4M5L6K",
        customerName: "Ivan Teo",
        customerEmail: "ivan.teo@email.com",
        customerPhone: "+1-555-3127",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK4K5J6H7G",
        customerName: "Natalie Chua",
        customerEmail: "natalie.chua@email.com",
        customerPhone: "+1-555-7812",
        partySize: 5,
        specialRequests: "Birthday cake service",
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      // Additional bookings for other restaurants to support reviews
      // Pasta Delights (Restaurant 1) - Bookings 40-51
      {
        confirmationCode: "BK40PAD001",
        customerName: "Marco Rossi",
        customerEmail: "marco.rossi@email.com",
        customerPhone: "62345679",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK41PAD002",
        customerName: "Anna Ferrari",
        customerEmail: "anna.ferrari@email.com",
        customerPhone: "62345680",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK42PAD003",
        customerName: "Luigi Bianchi",
        customerEmail: "luigi.bianchi@email.com",
        customerPhone: "62345681",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK43PAD004",
        customerName: "Sofia Colombo",
        customerEmail: "sofia.colombo@email.com",
        customerPhone: "62345682",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK44PAD005",
        customerName: "Giuseppe Rossi",
        customerEmail: "giuseppe.rossi@email.com",
        customerPhone: "62345683",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK45PAD006",
        customerName: "Maria Conti",
        customerEmail: "maria.conti@email.com",
        customerPhone: "62345684",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK46PAD007",
        customerName: "Valentina Moretti",
        customerEmail: "valentina.moretti@email.com",
        customerPhone: "62345685",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK47PAD008",
        customerName: "Paolo Moretti",
        customerEmail: "paolo.moretti@email.com",
        customerPhone: "62345686",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK48PAD009",
        customerName: "Elena Rossi",
        customerEmail: "elena.rossi@email.com",
        customerPhone: "62345687",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK49PAD010",
        customerName: "Antonio Bianchi",
        customerEmail: "antonio.bianchi@email.com",
        customerPhone: "62345688",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK50PAD011",
        customerName: "Giulia Rossi",
        customerEmail: "giulia.rossi@email.com",
        customerPhone: "62345689",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK51PAD012",
        customerName: "Davide Ferrari",
        customerEmail: "davide.ferrari@email.com",
        customerPhone: "62345690",
        partySize: 5,
        bookingDate: "2024-12-21",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },

      // Sakura Sushi & Grill (Restaurant 3) - Bookings 52-63
      {
        confirmationCode: "BK52SAK001",
        customerName: "Yuki Tanaka",
        customerEmail: "yuki.tanaka@email.com",
        customerPhone: "64567891",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK53SAK002",
        customerName: "Hiroshi Yamamoto",
        customerEmail: "hiroshi.yamamoto@email.com",
        customerPhone: "64567892",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK54SAK003",
        customerName: "Akiko Suzuki",
        customerEmail: "akiko.suzuki@email.com",
        customerPhone: "64567893",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK55SAK004",
        customerName: "Kenji Nakamura",
        customerEmail: "kenji.nakamura@email.com",
        customerPhone: "64567894",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK56SAK005",
        customerName: "Sakura Inoue",
        customerEmail: "sakura.inoue@email.com",
        customerPhone: "64567895",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK57SAK006",
        customerName: "Tomoe Sato",
        customerEmail: "tomoe.sato@email.com",
        customerPhone: "64567896",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK58SAK007",
        customerName: "Masaru Kobayashi",
        customerEmail: "masaru.kobayashi@email.com",
        customerPhone: "64567897",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK59SAK008",
        customerName: "Emiko Watanabe",
        customerEmail: "emiko.watanabe@email.com",
        customerPhone: "64567898",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK60SAK009",
        customerName: "Shiro Nakamura",
        customerEmail: "shiro.nakamura@email.com",
        customerPhone: "64567899",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK61SAK010",
        customerName: "Yoko Matsumoto",
        customerEmail: "yoko.matsumoto@email.com",
        customerPhone: "64567900",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK62SAK011",
        customerName: "Takeshi Yamada",
        customerEmail: "takeshi.yamada@email.com",
        customerPhone: "64567901",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK63SAK012",
        customerName: "Chiyo Sasaki",
        customerEmail: "chiyo.sasaki@email.com",
        customerPhone: "64567902",
        partySize: 5,
        bookingDate: "2024-12-21",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 3,
        fkSeatingId: null,
      },

      // Mama Rosa's Trattoria (Restaurant 4) - Bookings 64-74
      {
        confirmationCode: "BK64MRA001",
        customerName: "Rosa Nonna",
        customerEmail: "rosa.nonna@email.com",
        customerPhone: "69876544",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK65MRA002",
        customerName: "Carlo Bianchi",
        customerEmail: "carlo.bianchi@email.com",
        customerPhone: "69876545",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK66MRA003",
        customerName: "Lucia Rossi",
        customerEmail: "lucia.rossi@email.com",
        customerPhone: "69876546",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK67MRA004",
        customerName: "Francesca Moretti",
        customerEmail: "francesca.moretti@email.com",
        customerPhone: "69876547",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK68MRA005",
        customerName: "Giovanni Conti",
        customerEmail: "giovanni.conti@email.com",
        customerPhone: "69876548",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK69MRA006",
        customerName: "Angelina Rossi",
        customerEmail: "angelina.rossi@email.com",
        customerPhone: "69876549",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK70MRA007",
        customerName: "Michele Ferrari",
        customerEmail: "michele.ferrari@email.com",
        customerPhone: "69876550",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK71MRA008",
        customerName: "Vittoria Moretti",
        customerEmail: "vittoria.moretti@email.com",
        customerPhone: "69876551",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK72MRA009",
        customerName: "Salvatore Bianchi",
        customerEmail: "salvatore.bianchi@email.com",
        customerPhone: "69876552",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK73MRA010",
        customerName: "Marta Conti",
        customerEmail: "marta.conti@email.com",
        customerPhone: "69876553",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK74MRA011",
        customerName: "Rocco Rossi",
        customerEmail: "rocco.rossi@email.com",
        customerPhone: "69876554",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 4,
        fkSeatingId: null,
      },

      // Spice Route (Restaurant 5) - Bookings 75-86
      {
        confirmationCode: "BK75SPI001",
        customerName: "Raj Patel",
        customerEmail: "raj.patel@email.com",
        customerPhone: "63214568",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK76SPI002",
        customerName: "Priya Sharma",
        customerEmail: "priya.sharma@email.com",
        customerPhone: "63214569",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK77SPI003",
        customerName: "Arjun Kumar",
        customerEmail: "arjun.kumar@email.com",
        customerPhone: "63214570",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK78SPI004",
        customerName: "Neha Singh",
        customerEmail: "neha.singh@email.com",
        customerPhone: "63214571",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK79SPI005",
        customerName: "Vikram Malhotra",
        customerEmail: "vikram.malhotra@email.com",
        customerPhone: "63214572",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK80SPI006",
        customerName: "Anjali Verma",
        customerEmail: "anjali.verma@email.com",
        customerPhone: "63214573",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK81SPI007",
        customerName: "Rohit Gupta",
        customerEmail: "rohit.gupta@email.com",
        customerPhone: "63214574",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK82SPI008",
        customerName: "Divya Nair",
        customerEmail: "divya.nair@email.com",
        customerPhone: "63214575",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK83SPI009",
        customerName: "Sanjay Desai",
        customerEmail: "sanjay.desai@email.com",
        customerPhone: "63214576",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK84SPI010",
        customerName: "Pooja Iyer",
        customerEmail: "pooja.iyer@email.com",
        customerPhone: "63214577",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK85SPI011",
        customerName: "Anil Rao",
        customerEmail: "anil.rao@email.com",
        customerPhone: "63214578",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK86SPI012",
        customerName: "Kavya Reddy",
        customerEmail: "kavya.reddy@email.com",
        customerPhone: "63214579",
        partySize: 5,
        bookingDate: "2024-12-21",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 5,
        fkSeatingId: null,
      },

      // La Bella Notte (Restaurant 6) - Bookings 87-97
      {
        confirmationCode: "BK87LBN001",
        customerName: "Lorenzo Napoli",
        customerEmail: "lorenzo.napoli@email.com",
        customerPhone: "64321099",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK88LBN002",
        customerName: "Isabella Rossi",
        customerEmail: "isabella.rossi@email.com",
        customerPhone: "64321100",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK89LBN003",
        customerName: "Matteo Conti",
        customerEmail: "matteo.conti@email.com",
        customerPhone: "64321101",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK90LBN004",
        customerName: "Sofia Moretti",
        customerEmail: "sofia.moretti@email.com",
        customerPhone: "64321102",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK91LBN005",
        customerName: "Alessio Ferrari",
        customerEmail: "alessio.ferrari@email.com",
        customerPhone: "64321103",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK92LBN006",
        customerName: "Giuliana Bianchi",
        customerEmail: "giuliana.bianchi@email.com",
        customerPhone: "64321104",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK93LBN007",
        customerName: "Federico Romano",
        customerEmail: "federico.romano@email.com",
        customerPhone: "64321105",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK94LBN008",
        customerName: "Adriana Colombo",
        customerEmail: "adriana.colombo@email.com",
        customerPhone: "64321106",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK95LBN009",
        customerName: "Enrico Monti",
        customerEmail: "enrico.monti@email.com",
        customerPhone: "64321107",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK96LBN010",
        customerName: "Luciana Marinelli",
        customerEmail: "luciana.marinelli@email.com",
        customerPhone: "64321108",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK97LBN011",
        customerName: "Damiano Rossi",
        customerEmail: "damiano.rossi@email.com",
        customerPhone: "64321109",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 6,
        fkSeatingId: null,
      },

      // Escargot & Cie (Restaurant 7) - Bookings 98-109
      {
        confirmationCode: "BK98ECA001",
        customerName: "Pierre Dubois",
        customerEmail: "pierre.dubois@email.com",
        customerPhone: "69876322",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK99ECA002",
        customerName: "Margot Laurent",
        customerEmail: "margot.laurent@email.com",
        customerPhone: "69876323",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK100ECA003",
        customerName: "Claude Durand",
        customerEmail: "claude.durand@email.com",
        customerPhone: "69876324",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK101ECA004",
        customerName: "Amelie Martin",
        customerEmail: "amelie.martin@email.com",
        customerPhone: "69876325",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK102ECA005",
        customerName: "Sebastien Renaud",
        customerEmail: "sebastien.renaud@email.com",
        customerPhone: "69876326",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK103ECA006",
        customerName: "Delphine Moreau",
        customerEmail: "delphine.moreau@email.com",
        customerPhone: "69876327",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK104ECA007",
        customerName: "Arnaud Leclerc",
        customerEmail: "arnaud.leclerc@email.com",
        customerPhone: "69876328",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK105ECA008",
        customerName: "Nathalie Fontaine",
        customerEmail: "nathalie.fontaine@email.com",
        customerPhone: "69876329",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK106ECA009",
        customerName: "Guillaume Bernier",
        customerEmail: "guillaume.bernier@email.com",
        customerPhone: "69876330",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK107ECA010",
        customerName: "Claire Chamois",
        customerEmail: "claire.chamois@email.com",
        customerPhone: "69876331",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK108ECA011",
        customerName: "Laurent Petit",
        customerEmail: "laurent.petit@email.com",
        customerPhone: "69876332",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK109ECA012",
        customerName: "Isabelle Dufour",
        customerEmail: "isabelle.dufour@email.com",
        customerPhone: "69876333",
        partySize: 5,
        bookingDate: "2024-12-21",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 7,
        fkSeatingId: null,
      },

      // Arigato Ramen House (Restaurant 8) - Bookings 110-120
      {
        confirmationCode: "BK110ARH001",
        customerName: "Keiko Tanaka",
        customerEmail: "keiko.tanaka@email.com",
        customerPhone: "61357925",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK111ARH002",
        customerName: "Haruto Sato",
        customerEmail: "haruto.sato@email.com",
        customerPhone: "61357926",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK112ARH003",
        customerName: "Yuki Yamamoto",
        customerEmail: "yuki.yamamoto@email.com",
        customerPhone: "61357927",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK113ARH004",
        customerName: "Sakura Nakamura",
        customerEmail: "sakura.nakamura@email.com",
        customerPhone: "61357928",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK114ARH005",
        customerName: "Kaito Suzuki",
        customerEmail: "kaito.suzuki@email.com",
        customerPhone: "61357929",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK115ARH006",
        customerName: "Akane Yamada",
        customerEmail: "akane.yamada@email.com",
        customerPhone: "61357930",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK116ARH007",
        customerName: "Toshiro Kobayashi",
        customerEmail: "toshiro.kobayashi@email.com",
        customerPhone: "61357931",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK117ARH008",
        customerName: "Hinata Inoue",
        customerEmail: "hinata.inoue@email.com",
        customerPhone: "61357932",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK118ARH009",
        customerName: "Riku Watanabe",
        customerEmail: "riku.watanabe@email.com",
        customerPhone: "61357933",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK119ARH010",
        customerName: "Mizuki Nakamura",
        customerEmail: "mizuki.nakamura@email.com",
        customerPhone: "61357934",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK120ARH011",
        customerName: "Sora Matsumoto",
        customerEmail: "sora.matsumoto@email.com",
        customerPhone: "61357935",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 8,
        fkSeatingId: null,
      },

      // Tandoori Dreams (Restaurant 9) - Bookings 121-133
      {
        confirmationCode: "BK121TDI001",
        customerName: "Ashok Kumar",
        customerEmail: "ashok.kumar@email.com",
        customerPhone: "68246803",
        partySize: 2,
        bookingDate: "2024-12-10",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK122TDI002",
        customerName: "Meera Sharma",
        customerEmail: "meera.sharma@email.com",
        customerPhone: "68246804",
        partySize: 4,
        bookingDate: "2024-12-11",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK123TDI003",
        customerName: "Ravi Patel",
        customerEmail: "ravi.patel@email.com",
        customerPhone: "68246805",
        partySize: 3,
        bookingDate: "2024-12-12",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK124TDI004",
        customerName: "Sunita Gupta",
        customerEmail: "sunita.gupta@email.com",
        customerPhone: "68246806",
        partySize: 2,
        bookingDate: "2024-12-13",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK125TDI005",
        customerName: "Nikhil Singh",
        customerEmail: "nikhil.singh@email.com",
        customerPhone: "68246807",
        partySize: 5,
        bookingDate: "2024-12-14",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK126TDI006",
        customerName: "Divya Verma",
        customerEmail: "divya.verma@email.com",
        customerPhone: "68246808",
        partySize: 3,
        bookingDate: "2024-12-15",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK127TDI007",
        customerName: "Vikram Desai",
        customerEmail: "vikram.desai@email.com",
        customerPhone: "68246809",
        partySize: 4,
        bookingDate: "2024-12-16",
        bookingTime: "18:45",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK128TDI008",
        customerName: "Pooja Singh",
        customerEmail: "pooja.singh@email.com",
        customerPhone: "68246810",
        partySize: 2,
        bookingDate: "2024-12-17",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK129TDI009",
        customerName: "Sanjay Kumar",
        customerEmail: "sanjay.kumar@email.com",
        customerPhone: "68246811",
        partySize: 3,
        bookingDate: "2024-12-18",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK130TDI010",
        customerName: "Anjali Nair",
        customerEmail: "anjali.nair@email.com",
        customerPhone: "68246812",
        partySize: 4,
        bookingDate: "2024-12-19",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK131TDI011",
        customerName: "Rohit Iyer",
        customerEmail: "rohit.iyer@email.com",
        customerPhone: "68246813",
        partySize: 2,
        bookingDate: "2024-12-20",
        bookingTime: "18:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK132TDI012",
        customerName: "Kavya Rao",
        customerEmail: "kavya.rao@email.com",
        customerPhone: "68246814",
        partySize: 5,
        bookingDate: "2024-12-21",
        bookingTime: "19:30",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK133TDI013",
        customerName: "Amar Singh",
        customerEmail: "amar.singh@email.com",
        customerPhone: "68246815",
        partySize: 3,
        bookingDate: "2024-12-22",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 9,
        fkSeatingId: null,
      },
    ]);

    // Reviews for all restaurants - at least 10 per restaurant
    await Reviews.bulkCreate([
      // The Garden Bistro - 23 Reviews (Restaurant 2)
      {
        fkBookingId: 5,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Great birthday ambiance and attentive staff.",
      },
      {
        fkBookingId: 6,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Flavors were solid, pacing of courses could improve.",
      },
      {
        fkBookingId: 10,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Window seat request handled perfectly.",
      },
      {
        fkBookingId: 11,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Late evening booking, food still fresh.",
      },
      {
        fkBookingId: 16,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Excellent vegetarian options.",
      },
      {
        fkBookingId: 17,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Service was quick and friendly.",
      },
      {
        fkBookingId: 19,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Celebration handled nicely, minor wait at arrival.",
      },
      {
        fkBookingId: 21,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Lunch seating comfortable and quiet.",
      },
      {
        fkBookingId: 22,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Afternoon booking smooth, staff helpful.",
      },
      {
        fkBookingId: 23,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Allergy request respected and well executed.",
      },
      {
        fkBookingId: 24,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Evening rush handled efficiently.",
      },
      {
        fkBookingId: 26,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Menu variety appreciated.",
      },
      {
        fkBookingId: 27,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Good balance of seasoning and plating.",
      },
      {
        fkBookingId: 28,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Afternoon light perfect near window.",
      },
      {
        fkBookingId: 29,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Family dinner went flawlessly.",
      },
      {
        fkBookingId: 30,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Repeat visit—quality consistent.",
      },
      {
        fkBookingId: 31,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Quiet table delivered as requested.",
      },
      {
        fkBookingId: 33,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Birthday dessert presentation was great.",
      },
      {
        fkBookingId: 34,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Evening service punctual and warm.",
      },
      {
        fkBookingId: 35,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Anniversary details handled perfectly.",
      },
      {
        fkBookingId: 36,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Late booking still well staffed.",
      },
      {
        fkBookingId: 37,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Window preference granted, great view.",
      },
      {
        fkBookingId: 39,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Birthday cake service seamless.",
      },
      // Pasta Delights - 12 Reviews (Restaurant 1)
      {
        fkBookingId: 1,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Authentic homemade pasta, absolutely delicious!",
      },
      {
        fkBookingId: 2,
        fkRestaurantId: 1,
        rating: 2,
        comment: "Average!",
      },
      {
        fkBookingId: 3,
        fkRestaurantId: 1,
        rating: 4,
        comment: "Great pasta, a bit pricey but worth it.",
      },
      {
        fkBookingId: 40,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Staff was friendly and service was quick.",
      },
      {
        fkBookingId: 41,
        fkRestaurantId: 1,
        rating: 3,
        comment: "Good ambiance, flavors were alright.",
      },
      {
        fkBookingId: 42,
        fkRestaurantId: 1,
        rating: 5,
        comment: "The tiramisu was out of this world!",
      },
      {
        fkBookingId: 43,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Perfect for date night, very romantic.",
      },
      {
        fkBookingId: 44,
        fkRestaurantId: 1,
        rating: 4,
        comment: "Fresh ingredients, traditional recipes.",
      },
      {
        fkBookingId: 45,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Owner personally came to check on us!",
      },
      {
        fkBookingId: 46,
        fkRestaurantId: 1,
        rating: 4,
        comment: "Good portion sizes, great value.",
      },
      {
        fkBookingId: 47,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Wine selection complements the pasta perfectly.",
      },
      {
        fkBookingId: 48,
        fkRestaurantId: 1,
        rating: 5,
        comment: "Exceeded all expectations, truly authentic.",
      },

      // Sakura Sushi & Grill - 12 Reviews (Restaurant 3)
      {
        fkBookingId: 52,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Freshest sushi I've ever had. Outstanding!",
      },
      {
        fkBookingId: 53,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Chef's skill is evident in every piece.",
      },
      {
        fkBookingId: 54,
        fkRestaurantId: 3,
        rating: 4,
        comment: "Great atmosphere, slightly long wait.",
      },
      {
        fkBookingId: 55,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Authentic Japanese experience.",
      },
      {
        fkBookingId: 56,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Sashimi was buttery and delicious.",
      },
      {
        fkBookingId: 57,
        fkRestaurantId: 3,
        rating: 4,
        comment: "Good variety, quality ingredients.",
      },
      { fkBookingId: 58, fkRestaurantId: 3, rating: 5, comment: "Wonderful omakase experience!" },
      {
        fkBookingId: 59,
        fkRestaurantId: 3,
        rating: 4,
        comment: "Professional staff, great service.",
      },
      {
        fkBookingId: 60,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Best sushi in the city, hands down.",
      },
      {
        fkBookingId: 61,
        fkRestaurantId: 3,
        rating: 5,
        comment: "The tempura was crispy and perfect.",
      },
      {
        fkBookingId: 62,
        fkRestaurantId: 3,
        rating: 1,
        comment: "Expensive for the quality, won't return.",
      },
      {
        fkBookingId: 63,
        fkRestaurantId: 3,
        rating: 5,
        comment: "Incredible presentation and taste.",
      },

      // Mama Rosa's Trattoria - 11 Reviews (Restaurant 4)
      {
        fkBookingId: 64,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Grandma's recipes taste like home!",
      },
      {
        fkBookingId: 65,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Traditional Italian, perfectly executed.",
      },
      {
        fkBookingId: 66,
        fkRestaurantId: 4,
        rating: 4,
        comment: "Cozy family atmosphere, great food.",
      },
      {
        fkBookingId: 67,
        fkRestaurantId: 4,
        rating: 2,
        comment: "The lasagna is cold and tasteless!",
      },
      {
        fkBookingId: 68,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Authentic flavors, generous portions.",
      },
      { fkBookingId: 69, fkRestaurantId: 4, rating: 4, comment: "Great for special occasions." },
      {
        fkBookingId: 70,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Felt like eating at an Italian nonna's table.",
      },
      {
        fkBookingId: 71,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Handmade pasta, absolutely divine.",
      },
      {
        fkBookingId: 72,
        fkRestaurantId: 4,
        rating: 4,
        comment: "Warm hospitality and delicious food.",
      },
      {
        fkBookingId: 73,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Best marinara sauce ever tasted.",
      },
      {
        fkBookingId: 74,
        fkRestaurantId: 4,
        rating: 5,
        comment: "Cacio e pepe was perfectly balanced.",
      },

      // Spice Route - 12 Reviews (Restaurant 5)
      {
        fkBookingId: 75,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Authentic Indian spices, perfectly balanced.",
      },
      {
        fkBookingId: 76,
        fkRestaurantId: 5,
        rating: 5,
        comment: "The tandoor dishes are amazing!",
      },
      { fkBookingId: 77, fkRestaurantId: 5, rating: 4, comment: "Great flavors, good service." },
      {
        fkBookingId: 78,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Butter chicken was incredibly creamy.",
      },
      {
        fkBookingId: 79,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Naan bread was freshly made to perfection.",
      },
      {
        fkBookingId: 80,
        fkRestaurantId: 5,
        rating: 4,
        comment: "Vegetarian options are excellent.",
      },
      { fkBookingId: 81, fkRestaurantId: 5, rating: 5, comment: "Best biryani in the city!" },
      {
        fkBookingId: 82,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Authentic preparation, wonderful aromas.",
      },
      {
        fkBookingId: 83,
        fkRestaurantId: 5,
        rating: 4,
        comment: "Good spice levels, friendly staff.",
      },
      {
        fkBookingId: 84,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Curries have incredible depth of flavor.",
      },
      {
        fkBookingId: 85,
        fkRestaurantId: 5,
        rating: 5,
        comment: "Mango lassi was refreshing and delicious.",
      },
      {
        fkBookingId: 86,
        fkRestaurantId: 5,
        rating: 4,
        comment: "Consistent quality every time we visit.",
      },

      // La Bella Notte - 11 Reviews (Restaurant 6)
      { fkBookingId: 87, fkRestaurantId: 6, rating: 5, comment: "Modern Italian at its finest!" },
      {
        fkBookingId: 88,
        fkRestaurantId: 6,
        rating: 5,
        comment: "Wood-fired pizzas are absolutely perfect.",
      },
      {
        fkBookingId: 89,
        fkRestaurantId: 6,
        rating: 4,
        comment: "Beautiful plating and great taste.",
      },
      {
        fkBookingId: 90,
        fkRestaurantId: 6,
        rating: 5,
        comment: "Handmade pasta is so tender and flavorful.",
      },
      {
        fkBookingId: 91,
        fkRestaurantId: 6,
        rating: 5,
        comment: "Sophisticated yet unpretentious.",
      },
      {
        fkBookingId: 92,
        fkRestaurantId: 6,
        rating: 4,
        comment: "Great wine pairings recommended by staff.",
      },
      {
        fkBookingId: 93,
        fkRestaurantId: 6,
        rating: 5,
        comment: "Crust on the pizza was simply divine.",
      },
      {
        fkBookingId: 94,
        fkRestaurantId: 6,
        rating: 5,
        comment: "Every dish was a culinary masterpiece.",
      },
      {
        fkBookingId: 95,
        fkRestaurantId: 6,
        rating: 4,
        comment: "Excellent service, beautiful ambiance.",
      },
      {
        fkBookingId: 96,
        fkRestaurantId: 6,
        rating: 5,
        comment: "The truffle risotto was extraordinary.",
      },
      {
        fkBookingId: 97,
        fkRestaurantId: 6,
        rating: 5,
        comment: "One of the best dining experiences ever!",
      },

      // Escargot & Cie - 12 Reviews (Restaurant 7)
      {
        fkBookingId: 98,
        fkRestaurantId: 7,
        rating: 5,
        comment: "Truly Parisian, authentic French cuisine!",
      },
      {
        fkBookingId: 99,
        fkRestaurantId: 7,
        rating: 5,
        comment: "Classic dishes prepared with mastery.",
      },
      {
        fkBookingId: 100,
        fkRestaurantId: 7,
        rating: 4,
        comment: "Elegant setting, impeccable service.",
      },
      {
        fkBookingId: 101,
        fkRestaurantId: 7,
        rating: 5,
        comment: "Coq au vin was tender and rich.",
      },
      { fkBookingId: 102, fkRestaurantId: 7, rating: 5, comment: "Wine list is outstanding." },
      {
        fkBookingId: 103,
        fkRestaurantId: 7,
        rating: 4,
        comment: "Duck confit was perfectly crispy.",
      },
      { fkBookingId: 104, fkRestaurantId: 7, rating: 5, comment: "Escargot melts in your mouth!" },
      { fkBookingId: 105, fkRestaurantId: 7, rating: 5, comment: "Sophisticated French dining." },
      {
        fkBookingId: 106,
        fkRestaurantId: 7,
        rating: 4,
        comment: "Lovely ambiance, romantic atmosphere.",
      },
      {
        fkBookingId: 107,
        fkRestaurantId: 7,
        rating: 5,
        comment: "Beef bourguignon was exceptional.",
      },
      {
        fkBookingId: 108,
        fkRestaurantId: 7,
        rating: 5,
        comment: "Best French food outside of Paris!",
      },
      {
        fkBookingId: 109,
        fkRestaurantId: 7,
        rating: 4,
        comment: "Soufflé was perfectly risen and fluffy.",
      },

      // Arigato Ramen House - 11 Reviews (Restaurant 8)
      {
        fkBookingId: 110,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Best ramen broth I've ever had!",
      },
      {
        fkBookingId: 111,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Authentic tonkotsu, silky smooth.",
      },
      {
        fkBookingId: 112,
        fkRestaurantId: 8,
        rating: 4,
        comment: "Cozy atmosphere, friendly service.",
      },
      {
        fkBookingId: 113,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Noodles have perfect chewiness.",
      },
      {
        fkBookingId: 114,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Toppings are fresh and generous.",
      },
      { fkBookingId: 115, fkRestaurantId: 8, rating: 4, comment: "Great value for the quality." },
      {
        fkBookingId: 116,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Miso ramen is absolutely delicious.",
      },
      {
        fkBookingId: 117,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Worth the wait during peak hours.",
      },
      {
        fkBookingId: 118,
        fkRestaurantId: 8,
        rating: 4,
        comment: "Chashu pork is tender and flavorful.",
      },
      { fkBookingId: 119, fkRestaurantId: 8, rating: 5, comment: "Takes you straight to Japan." },
      {
        fkBookingId: 120,
        fkRestaurantId: 8,
        rating: 5,
        comment: "Best ramen in the neighborhood!",
      },

      // Tandoori Dreams - 13 Reviews (Restaurant 9)
      {
        fkBookingId: 121,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Tandoori chicken is incredibly juicy!",
      },
      {
        fkBookingId: 122,
        fkRestaurantId: 9,
        rating: 5,
        comment: "North Indian specialties done right.",
      },
      {
        fkBookingId: 123,
        fkRestaurantId: 9,
        rating: 4,
        comment: "Aromatic spices, authentic preparation.",
      },
      {
        fkBookingId: 124,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Paneer tikka was perfectly charred.",
      },
      {
        fkBookingId: 125,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Dal tadka is comfort food at its best.",
      },
      {
        fkBookingId: 126,
        fkRestaurantId: 9,
        rating: 4,
        comment: "Roti is freshly made in-house.",
      },
      {
        fkBookingId: 127,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Chicken do pyaza has great depth.",
      },
      {
        fkBookingId: 128,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Samosas are crispy and flavorful.",
      },
      { fkBookingId: 129, fkRestaurantId: 9, rating: 4, comment: "Excellent vegetarian options." },
      {
        fkBookingId: 130,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Gulab jamun is sweet perfection.",
      },
      { fkBookingId: 131, fkRestaurantId: 9, rating: 5, comment: "Best Indian food in the area!" },
      { fkBookingId: 132, fkRestaurantId: 9, rating: 4, comment: "Staff is very knowledgeable." },
      {
        fkBookingId: 133,
        fkRestaurantId: 9,
        rating: 5,
        comment: "Quality and consistency are top-notch.",
      },
    ]);

    // Add menu dietary types for each restaurant
    await Menus.bulkCreate([
      // Pasta Delights - Italian restaurant (Restaurant 1)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/pasta_delights_vegetarian.pdf",
        fkRestaurantId: 1,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/pasta_delights_vegan.pdf",
        fkRestaurantId: 1,
      },
      // The Garden Bistro - French restaurant (Restaurant 2)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/garden_bistro_vegetarian.pdf",
        fkRestaurantId: 2,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/garden_bistro_halal.pdf",
        fkRestaurantId: 2,
      },
      // Sakura Sushi & Grill - Japanese restaurant (Restaurant 3)
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/sakura_sushi_vegan.pdf",
        fkRestaurantId: 3,
      },
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/sakura_sushi_vegetarian.pdf",
        fkRestaurantId: 3,
      },
      // Mama Rosa's Trattoria - Italian restaurant (Restaurant 4)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/mama_rosas_vegetarian.pdf",
        fkRestaurantId: 4,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/mama_rosas_vegan.pdf",
        fkRestaurantId: 4,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/mama_rosas_halal.pdf",
        fkRestaurantId: 4,
      },
      // Spice Route - Indian restaurant (Restaurant 5)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/spice_route_vegetarian.pdf",
        fkRestaurantId: 5,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/spice_route_vegan.pdf",
        fkRestaurantId: 5,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/spice_route_halal.pdf",
        fkRestaurantId: 5,
      },
      // La Bella Notte - Italian restaurant (Restaurant 6)
      {
        menuTypes: "Vegetarian",
        menuFilepath:
          "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
        fkRestaurantId: 6,
      },
      {
        menuTypes: "Vegan",
        menuFilepath:
          "https://images.unsplash.com/photo-1495195134817-aeb325ef3c4f?w=800&h=600&fit=crop",
        fkRestaurantId: 6,
      },
      // Escargot & Cie - French restaurant (Restaurant 7)
      {
        menuTypes: "Vegetarian",
        menuFilepath:
          "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
        fkRestaurantId: 7,
      },
      {
        menuTypes: "Halal",
        menuFilepath:
          "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
        fkRestaurantId: 7,
      },
      // Arigato Ramen House - Japanese restaurant (Restaurant 8)
      {
        menuTypes: "Vegan",
        menuFilepath:
          "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop",
        fkRestaurantId: 8,
      },
      {
        menuTypes: "Vegetarian",
        menuFilepath:
          "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&h=600&fit=crop",
        fkRestaurantId: 8,
      },
      // Tandoori Dreams - Indian restaurant (Restaurant 9)
      {
        menuTypes: "Vegetarian",
        menuFilepath:
          "https://images.unsplash.com/photo-1596040306806-35f96ec48b93?w=800&h=600&fit=crop",
        fkRestaurantId: 9,
      },
      {
        menuTypes: "Vegan",
        menuFilepath:
          "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&h=600&fit=crop",
        fkRestaurantId: 9,
      },
      {
        menuTypes: "Halal",
        menuFilepath:
          "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
        fkRestaurantId: 9,
      },
    ]);

    await Promotions.bulkCreate([
      {
        description: "20% off on all main courses",
        discount: "LPRDINE20",
        startAt: "2025-11-01",
        endAt: "2025-11-30",
        termsNCond: "Valid for dine-in only. Not applicable to beverages.",
        fkRestaurantId: 1,
      },
      {
        description: "20% off on all main courses",
        discount: "LPRDINE20",
        startAt: "2024-11-01",
        endAt: "2024-11-30",
        termsNCond: "Valid for dine-in only. Not applicable to beverages.",
        fkRestaurantId: 1,
      },
      {
        description: "Season of giving! Free tiramisu for every $50 spent",
        discount: "TIRAFREE20",
        startAt: "2025-11-22",
        endAt: "2025-11-30",
        termsNCond: "Valid for dine-in only. Limited to one redemption per table.",
        fkRestaurantId: 1,
      },
      {
        description: "20% off on all main courses",
        discount: "LPRDINE20",
        startAt: "2026-11-01",
        endAt: "2026-11-30",
        termsNCond: "Valid for dine-in only. Not applicable to beverages.",
        fkRestaurantId: 1,
      },
      {
        description: "Buy 1 sushi roll, get 1 free",
        discount: "SUSHI2FOR1",
        startAt: "2024-11-05",
        endAt: "2024-11-20",
        termsNCond: "Valid on selected menu items only. One per customer.",
        fkRestaurantId: 3,
      },
      {
        description: "Happy Hour: 50% off appetizers 5-7 PM",
        discount: "HAPPYHOUR50",
        startAt: "2025-11-01",
        endAt: "2025-12-31",
        termsNCond: "Valid Monday to Friday, 5-7 PM. Dine-in only.",
        fkRestaurantId: 2,
      },
      {
        description: "Birthday special: Complimentary dessert",
        discount: "BDAY2024",
        startAt: "2025-11-01",
        endAt: "2025-12-31",
        termsNCond: "Valid on your birthday month. Must show valid ID.",
        fkRestaurantId: 5,
      },
      {
        description: "Family Combo Package: 30% discount",
        discount: "FAMILY30",
        startAt: "2025-11-10",
        endAt: "2025-12-25",
        termsNCond: "Valid for 4+ people. Not combinable with other offers.",
        fkRestaurantId: 4,
      },
    ]);

    console.log("Initial Data Created!");
  } catch (err) {
    console.log("Something went wrong! " + err);
  }
};
