const { Addresses } = require("../src/schemas/addresses.js");
const { Restaurants } = require("../src/schemas/restaurants.js");
const { SeatingPlans } = require("../src/schemas/seatingPlans.js");
const { Bookings } = require("../src/schemas/bookings.js");
const { Promotions } = require("../src/schemas/promotions.js");
const { Reviews } = require("../src/schemas/reviews.js");
const { Menus } = require("../src/schemas/menus.js");

module.exports.LoadData = async () => {
  try {
    await Addresses.bulkCreate([
      {
        addressLine1: "123 Orchard Road",
        country: "Singapore",
        city: "Orchard",
        state: "Singapore",
        postalCode: "238801",
      },
      {
        addressLine1: "456 Marina Bay Street",
        country: "Singapore",
        city: "Marina Bay",
        state: "Singapore",
        postalCode: "018972",
      },
      {
        addressLine1: "789 Clementi Avenue 2",
        country: "Singapore",
        city: "Clementi",
        state: "Singapore",
        postalCode: "129603",
      },
      {
        addressLine1: "321 Bukit Merah View",
        country: "Singapore",
        city: "Bukit Merah",
        state: "Singapore",
        postalCode: "150321",
      },
      {
        addressLine1: "654 Bedok Reservoir Road",
        country: "Singapore",
        city: "Bedok",
        state: "Singapore",
        postalCode: "479261",
      },
    ]);

    await Restaurants.bulkCreate([
      {
        restaurantName: "Pasta Delights",
        description: "A place for all to enjoy homemade pasta",
        cuisine: "Italian",
        fkAddressId: 1,
        phone: "(555) 876-5544",
        email: "contact@pasta.com",
        imageUrl:
          "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=1200&h=800&fit=crop",
        openingTime: "11:00:00",
        closingTime: "22:00:00",
      },
      {
        restaurantName: "The Garden Bistro",
        description: "An elegant French bistro offering classic dishes with a modern twist.",
        cuisine: "French",
        fkAddressId: 2,
        phone: "+1-555-0123",
        email: "reservations@gardenbistro.com",
        imageUrl:
          "https://images.unsplash.com/photo-1744313983217-e24a659bf7c1?w=1200&h=800&fit=crop",
        openingTime: "11:00:00",
        closingTime: "22:00:00",
      },
      {
        restaurantName: "Sakura Sushi & Grill",
        cuisine: "Japanese",
        description: "Fresh sushi and authentic Japanese cuisine in a contemporary setting.",
        fkAddressId: 3,
        phone: "+1-555-0456",
        email: "info@sakurasushi.com",
        imageUrl:
          "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=1200&h=800&fit=crop",
        openingTime: "12:00:00",
        closingTime: "23:00:00",
      },
      {
        restaurantName: "Mama Rosa's Trattoria",
        cuisine: "Italian",
        description: "Traditional Italian family recipes passed down through generations.",
        fkAddressId: 4,
        phone: "+1-555-0789",
        email: "ciao@mamarosas.com",
        imageUrl:
          "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1200&h=800&fit=crop",
        openingTime: "17:00:00",
        closingTime: "23:00:00",
      },
      {
        restaurantName: "Spice Route",
        cuisine: "Indian",
        description:
          "Authentic Indian cuisine with aromatic spices and traditional cooking methods.",
        fkAddressId: 5,
        phone: "+1-555-0321",
        email: "hello@spiceroute.com",
        imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&h=800&fit=crop",
        openingTime: "11:30:00",
        closingTime: "23:00:00",
      },
    ]);

    await SeatingPlans.bulkCreate([
      {
        pax: 2,
        tableType: "indoor",
        tableNumber: "T1",
        fkRestaurantId: 1,
        x: 120,
        y: 80,
      },
      {
        pax: 4,
        tableType: "indoor",
        tableNumber: "T2",
        fkRestaurantId: 1,
        x: 220,
        y: 80,
      },
      {
        pax: 6,
        tableType: "vip",
        tableNumber: "VIP-1",
        fkRestaurantId: 1,
        x: 420,
        y: 200,
      },
      {
        pax: 2,
        tableType: "outdoor",
        tableNumber: "PATIO-1",
        fkRestaurantId: 1,
        x: 80,
        y: 260,
      },
      {
        pax: 4,
        tableType: "indoor",
        tableNumber: "T1",
        fkRestaurantId: 2,
        x: 140,
        y: 100,
      },
    ]);

    await Bookings.bulkCreate([
      {
        confirmationCode: "BK6F8K9J2L",
        customerName: "John Smith",
        customerEmail: "john.smith@email.com",
        customerPhone: "+1-555-1234",
        partySize: 2,
        specialRequests: "Window table preferred",
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "confirmed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK4N5M3P9X",
        customerName: "Sarah Johnson",
        customerEmail: "sarah.j@email.com",
        customerPhone: "+1-555-5678",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "pending",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7R2W5T8Q",
        customerName: "Michael Chen",
        customerEmail: "michael.chen@email.com",
        customerPhone: "+1-555-9012",
        partySize: 3,
        specialRequests: "Vegetarian options required",
        bookingDate: "2025-11-18",
        bookingTime: "19:00", // TIME format (24-hour)
        status: "confirmed",
        fkRestaurantId: 1,
        fkSeatingId: null,
      },
      // Ginna's Demo: 36 Bookings - The Garden Bistro - December 2024
      {
        confirmationCode: "BK8A1B2C3D",
        customerName: "Emily Davis",
        customerEmail: "emily.davis@email.com",
        customerPhone: "+1-555-2468",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-18",
        bookingTime: "19:30",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK9E4F5G6H",
        customerName: "Robert Wilson",
        customerEmail: "robert.w@email.com",
        customerPhone: "+1-555-1357",
        partySize: 4,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK1I7J8K9L",
        customerName: "Jessica Martinez",
        customerEmail: "jessica.m@email.com",
        customerPhone: "+1-555-9753",
        partySize: 3,
        specialRequests: "Allergic to shellfish",
        bookingDate: "2024-12-12",
        bookingTime: "20:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2M0N1O2P",
        customerName: "David Brown",
        customerEmail: "david.brown@email.com",
        customerPhone: "+1-555-3579",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-10",
        bookingTime: "19:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK3Q4R5S6T",
        customerName: "Lisa Anderson",
        customerEmail: "lisa.a@email.com",
        customerPhone: "+1-555-7531",
        partySize: 5,
        specialRequests: "High chair needed",
        bookingDate: "2024-12-20",
        bookingTime: "17:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4U5V6W7P",
        customerName: "James Taylor",
        customerEmail: "james.t@email.com",
        customerPhone: "+1-555-8642",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-21",
        bookingTime: "18:45",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5Y6Z7A8B",
        customerName: "Patricia Lee",
        customerEmail: "patricia.lee@email.com",
        customerPhone: "+1-555-2468",
        partySize: 3,
        specialRequests: "Window seat preferred",
        bookingDate: "2024-12-22",
        bookingTime: "19:15",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6C7D8E9F",
        customerName: "Thomas Garcia",
        customerEmail: "thomas.g@email.com",
        customerPhone: "+1-555-4820",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-09",
        bookingTime: "20:30",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK7G8H9I0J",
        customerName: "Amanda White",
        customerEmail: "amanda.white@email.com",
        customerPhone: "+1-555-1928",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-08",
        bookingTime: "18:15",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8K9L0M1N",
        customerName: "Christopher Moore",
        customerEmail: "chris.moore@email.com",
        customerPhone: "+1-555-3746",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-23",
        bookingTime: "19:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK9O1P2Q3R",
        customerName: "Michelle Rodriguez",
        customerEmail: "michelle.r@email.com",
        customerPhone: "+1-555-5564",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-07",
        bookingTime: "20:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0S3T4U5V",
        customerName: "Kevin Jackson",
        customerEmail: "kevin.j@email.com",
        customerPhone: "+1-555-7382",
        partySize: 5,
        specialRequests: "Celebration dinner",
        bookingDate: "2024-12-24",
        bookingTime: "17:45",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK1A2B3C4D",
        customerName: "Olivia Green",
        customerEmail: "olivia.green@email.com",
        customerPhone: "+1-555-1235",
        partySize: 4,
        specialRequests: "Vegetarian meal",
        bookingDate: "2024-12-01",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2E3F4G5H",
        customerName: "Ethan Brown",
        customerEmail: "ethan.brown@email.com",
        customerPhone: "+1-555-6789",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-02",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3I4J5K6L",
        customerName: "Sophia White",
        customerEmail: "sophia.white@email.com",
        customerPhone: "+1-555-2468",
        partySize: 3,
        specialRequests: "Window seat",
        bookingDate: "2024-12-03",
        bookingTime: "20:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4M5N6O7P",
        customerName: "Liam Johnson",
        customerEmail: "liam.johnson@email.com",
        customerPhone: "+1-555-1357",
        partySize: 5,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-04",
        bookingTime: "17:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5Q6R7S8T",
        customerName: "Emma Davis",
        customerEmail: "emma.davis@email.com",
        customerPhone: "+1-555-9753",
        partySize: 6,
        specialRequests: null,
        bookingDate: "2024-12-05",
        bookingTime: "21:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6U7V8W9X",
        customerName: "Noah Wilson",
        customerEmail: "noah.wilson@email.com",
        customerPhone: "+1-555-3579",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-06",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7Y8Z9A1B",
        customerName: "Ava Martinez",
        customerEmail: "ava.martinez@email.com",
        customerPhone: "+1-555-7531",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-07",
        bookingTime: "15:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8C9D1E2F",
        customerName: "James Garcia",
        customerEmail: "james.garcia@email.com",
        customerPhone: "+1-555-8642",
        partySize: 3,
        specialRequests: "Allergic to peanuts",
        bookingDate: "2024-12-08",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK9G1H2I3J",
        customerName: "Isabella Rodriguez",
        customerEmail: "isabella.rodriguez@email.com",
        customerPhone: "+1-555-4820",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0K1L2M3N",
        customerName: "Benjamin Moore",
        customerEmail: "benjamin.moore@email.com",
        customerPhone: "+1-555-1928",
        partySize: 5,
        specialRequests: "High chair needed",
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "cancelled",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK1O2P3Q4R",
        customerName: "Mia Taylor",
        customerEmail: "mia.taylor@email.com",
        customerPhone: "+1-555-5564",
        partySize: 4,
        specialRequests: "Vegan options",
        bookingDate: "2024-12-18",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK2S3T4U5V",
        customerName: "Lucas Anderson",
        customerEmail: "lucas.anderson@email.com",
        customerPhone: "+1-555-7382",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-19",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3W4X5Y6Z",
        customerName: "Charlotte Lee",
        customerEmail: "charlotte.lee@email.com",
        customerPhone: "+1-555-2468",
        partySize: 2,
        specialRequests: "Window seat",
        bookingDate: "2024-12-19",
        bookingTime: "14:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK4A5B6C7D",
        customerName: "Henry White",
        customerEmail: "henry.white@email.com",
        customerPhone: "+1-555-1235",
        partySize: 6,
        specialRequests: "Celebration dinner",
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK5E6F7G8H",
        customerName: "Amelia Green",
        customerEmail: "amelia.green@email.com",
        customerPhone: "+1-555-6789",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK6I7J8K9L",
        customerName: "Jack Brown",
        customerEmail: "jack.brown@email.com",
        customerPhone: "+1-555-1357",
        partySize: 2,
        specialRequests: "Quiet table",
        bookingDate: "2024-12-25",
        bookingTime: "12:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK7M8N9O1P",
        customerName: "Harper Johnson",
        customerEmail: "harper.johnson@email.com",
        customerPhone: "+1-555-9753",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "15:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK8Q9R1S2T",
        customerName: "Ella Wilson",
        customerEmail: "ella.wilson@email.com",
        customerPhone: "+1-555-3579",
        partySize: 5,
        specialRequests: "Birthday celebration",
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK9U1V2W3X",
        customerName: "Alexander Martinez",
        customerEmail: "alex.martinez@email.com",
        customerPhone: "+1-555-7531",
        partySize: 4,
        specialRequests: null,
        bookingDate: "2024-12-19",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: 5,
      },
      {
        confirmationCode: "BK0Z1Y2X3W",
        customerName: "Grace Lim",
        customerEmail: "grace.lim@email.com",
        customerPhone: "+1-555-2389",
        partySize: 2,
        specialRequests: "Anniversary celebration",
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK1T2U3V4W",
        customerName: "Daniel Ng",
        customerEmail: "daniel.ng@email.com",
        customerPhone: "+1-555-8492",
        partySize: 3,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK2S3R4Q5P",
        customerName: "Fiona Tan",
        customerEmail: "fiona.tan@email.com",
        customerPhone: "+1-555-6734",
        partySize: 4,
        specialRequests: "Window seat preferred",
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK3N4M5L6K",
        customerName: "Ivan Teo",
        customerEmail: "ivan.teo@email.com",
        customerPhone: "+1-555-3127",
        partySize: 2,
        specialRequests: null,
        bookingDate: "2024-12-25",
        bookingTime: "18:00",
        status: "no_show",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
      {
        confirmationCode: "BK4K5J6H7G",
        customerName: "Natalie Chua",
        customerEmail: "natalie.chua@email.com",
        customerPhone: "+1-555-7812",
        partySize: 5,
        specialRequests: "Birthday cake service",
        bookingDate: "2024-12-25",
        bookingTime: "19:00",
        status: "completed",
        fkRestaurantId: 2,
        fkSeatingId: null,
      },
    ]);

    // Ginna's Demo: 23 Reviews - The Garden Bistro - December 2024
    await Reviews.bulkCreate([
      {
        fkBookingId: 5,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Great birthday ambiance and attentive staff.",
      },
      {
        fkBookingId: 6,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Flavors were solid, pacing of courses could improve.",
      },
      {
        fkBookingId: 10,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Window seat request handled perfectly.",
      },
      {
        fkBookingId: 11,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Late evening booking, food still fresh.",
      },
      {
        fkBookingId: 16,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Excellent vegetarian options.",
      },
      {
        fkBookingId: 17,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Service was quick and friendly.",
      },
      {
        fkBookingId: 19,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Celebration handled nicely, minor wait at arrival.",
      },
      {
        fkBookingId: 21,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Lunch seating comfortable and quiet.",
      },
      {
        fkBookingId: 22,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Afternoon booking smooth, staff helpful.",
      },
      {
        fkBookingId: 23,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Allergy request respected and well executed.",
      },
      {
        fkBookingId: 24,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Evening rush handled efficiently.",
      },
      {
        fkBookingId: 26,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Menu variety appreciated.",
      },
      {
        fkBookingId: 27,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Good balance of seasoning and plating.",
      },
      {
        fkBookingId: 28,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Afternoon light perfect near window.",
      },
      {
        fkBookingId: 29,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Family dinner went flawlessly.",
      },
      {
        fkBookingId: 30,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Repeat visit—quality consistent.",
      },
      {
        fkBookingId: 31,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Quiet table delivered as requested.",
      },
      {
        fkBookingId: 33,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Birthday dessert presentation was great.",
      },
      {
        fkBookingId: 34,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Evening service punctual and warm.",
      },
      {
        fkBookingId: 35,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Anniversary details handled perfectly.",
      },
      {
        fkBookingId: 36,
        fkRestaurantId: 2,
        rating: 4,
        comment: "Late booking still well staffed.",
      },
      {
        fkBookingId: 37,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Window preference granted, great view.",
      },
      {
        fkBookingId: 39,
        fkRestaurantId: 2,
        rating: 5,
        comment: "Birthday cake service seamless.",
      },
    ]);

    // Add menu dietary types for each restaurant
    await Menus.bulkCreate([
      // Pasta Delights - Italian restaurant (Restaurant 1)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/pasta_delights_vegetarian.pdf",
        fkRestaurantId: 1,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/pasta_delights_vegan.pdf",
        fkRestaurantId: 1,
      },
      // The Garden Bistro - French restaurant (Restaurant 2)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/garden_bistro_vegetarian.pdf",
        fkRestaurantId: 2,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/garden_bistro_halal.pdf",
        fkRestaurantId: 2,
      },
      // Sakura Sushi & Grill - Japanese restaurant (Restaurant 3)
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/sakura_sushi_vegan.pdf",
        fkRestaurantId: 3,
      },
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/sakura_sushi_vegetarian.pdf",
        fkRestaurantId: 3,
      },
      // Mama Rosa's Trattoria - Italian restaurant (Restaurant 4)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/mama_rosas_vegetarian.pdf",
        fkRestaurantId: 4,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/mama_rosas_vegan.pdf",
        fkRestaurantId: 4,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/mama_rosas_halal.pdf",
        fkRestaurantId: 4,
      },
      // Spice Route - Indian restaurant (Restaurant 5)
      {
        menuTypes: "Vegetarian",
        menuFilepath: "/menus/spice_route_vegetarian.pdf",
        fkRestaurantId: 5,
      },
      {
        menuTypes: "Vegan",
        menuFilepath: "/menus/spice_route_vegan.pdf",
        fkRestaurantId: 5,
      },
      {
        menuTypes: "Halal",
        menuFilepath: "/menus/spice_route_halal.pdf",
        fkRestaurantId: 5,
      },
    ]);

    await Promotions.bulkCreate([
      {
        description: "20% off on all main courses",
        //1st discount (do you mean discountCode)?
        discount: "LPRDINE20",
        startAt: "2024-11-01",
        endAt: "2024-11-30",
        termsNCond: "Valid for dine-in only. Not applicable to beverages.",
        //2nd discount
        discount: "20%",
        fkRestaurantId: 1,
      },
      {
        description: "Buy 1 sushi roll, get 1 free",
        discount: "SUSHI2FOR1",
        startAt: "2024-11-05",
        endAt: "2024-11-20",
        termsNCond: "Valid on selected menu items only. One per customer.",
        discount: "BOGO",
        fkRestaurantId: 3,
      },
      {
        description: "Happy Hour: 50% off appetizers 5-7 PM",
        discount: "HAPPYHOUR50",
        startAt: "2025-11-01",
        endAt: "2025-12-31",
        termsNCond: "Valid Monday to Friday, 5-7 PM. Dine-in only.",
        discount: "50%",
        fkRestaurantId: 2,
      },
      {
        description: "Birthday special: Complimentary dessert",
        discount: "BDAY2024",
        startAt: "2025-11-01",
        endAt: "2025-12-31",
        termsNCond: "Valid on your birthday month. Must show valid ID.",
        discount: "Free Dessert",
        fkRestaurantId: 5,
      },
      {
        description: "Family Combo Package: 30% discount",
        discount: "FAMILY30",
        startAt: "2025-11-10",
        endAt: "2025-12-25",
        termsNCond: "Valid for 4+ people. Not combinable with other offers.",
        discount: "30%",
        fkRestaurantId: 4,
      },
    ]);

    console.log("Initial Data Created!");
  } catch (err) {
    console.log("Something went wrong! " + err);
  }
};
